### ISSUE TITLE
Get caching to work on Node.js

### ISSUE THREAD

**Issue by ariutta** [ariutta/jsonld-rx#1]
Enabling `superagent-cache` causes the tests involving redirection to fail, e.g., [Loading a document with a redirect should use the redirected URL as document base](https://github.com/json-ld/json-ld.org/blob/b2c57989c1d72faf5d6fe788c0523120d8098136/test-suite/tests/remote-doc-manifest.jsonld#L47).

To enable `superagent-cache`, first make sure you've installed the library and set up the tests as described in the [main README](https://github.com/ariutta/jsonld-rx/blob/master/README.md). Then uncomment the commented-out code block that starts here:
https://github.com/ariutta/jsonld-rx/blob/master/lib/after.js#L3
Finally, save the file, rebuild (`npm run build`) and re-run the tests (`npm test`).

If `remote-doc-0005-in.jsonld`, `remote-doc-0006-in.jsonld` and `remote-doc-0007-in.jsonld`, all redirect to `remote-doc-0001-in.jsonld`, it appears that requesting any one of the first three before requesting `remote-doc-0001-in.jsonld` makes the tests pass, but if `remote-doc-0001-in.jsonld` is requested first, the tests will not pass. Commented out example of this: https://github.com/ariutta/jsonld-rx/blob/master/lib/after.js#L47

**Comment by jpodwys** [comment]
Is superagent-cache still causing issues for you?

**Comment by ariutta** [comment]
Thanks for checking. It's working nicely. Closing this issue now :)

**Comment by jpodwys** [comment]
Ok, glad to hear it.
